#Configuraciones Globales de Inventario
#Wed Sep 02 14:04:30 VET 2026
auto.frecuencia=0.0
auto.ruta=
auto.unidad=MINUTOS
db.password=
db.url=jdbc\:sqlite\:inventario.db
db.user=root
replica.ruta=
tasa.eur=929.09083243
tasa.ves=801.1752
