#Configuraciones Globales de Inventario
#Tue Sep 01 15:35:57 VET 2026
auto.frecuencia=0.0
auto.ruta=
auto.unidad=MINUTOS
db.password=
db.url=jdbc\:sqlite\:inventario.db
db.user=root
replica.ruta=
tasa.eur=926.55312212
tasa.ves=798.326
